version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker

      
  test_server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server  
      - run:
          name: Running server tests
          command: npm test
          working_directory: ./server
                    
  test_client:
    executor:
      name: node/default
    steps:
      - checkout       
      - run:
          command: npm install
          working_directory: ./client      
      - run:
          name: Running server tests
          command: npm test
          working_directory: ./client
          
  create_docker_images:
    machine: true
    steps:
      - checkout          
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "matwitkowski" --password-stdin
            sudo docker build ./db -t matwitkowski/database_image
            sudo docker push matwitkowski/database_image:latest
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "matwitkowski" --password-stdin
            sudo docker build ./server -t matwitkowski/server_image
            sudo docker push matwitkowski/server_image
      - run:
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "matwitkowski" --password-stdin
            sudo docker build ./client -t matwitkowski/client_image
            sudo docker push matwitkowski/client_image

          
workflows:
    build-and-test:
      jobs:
        - build:
          filters:
            branches:
              only:
                - master
        - test_server:
            filters:
              branches:
                only:
                  - master
            requires:
                - build
        - test_client:
            filters:
              branches:
                only:
                  - master
            requires:
                - build
                
        - create_docker_images:
            requires:
              - test_server
              - test_client
